name: e2e-sgx
on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Images to build before provisioning pull on worker'
        required: true
        default: 'intel-sgx-plugin intel-sgx-initcontainer intel-sgx-admissionwebhook'

env:
  IMAGES: ${{ github.event.inputs.images }}

jobs:
  e2e-sgx:
    name: e2e-sgx
    runs-on: [self-hosted, linux, x64, sgx]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Describe test environment
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Images: ${{ github.event.inputs.images }}"
      - name: Wait for ready state
        run: ../../../../bmetal/actions-bmetal-runstage.sh waitready
      - name: Prepare test environment
        run: ../../../../bmetal/actions-bmetal-runstage.sh prepare
      - name: Run tests
        run: ../../../../bmetal/actions-bmetal-runstage.sh test
